# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bayesian Built Environment Network Model
#' @param y vector of outcomes
#' @param Z matrix of subject covariates
#' @param DD sparse matrix of subject distances in basis format
#' @param rpc array of regression parameter settings
#' @param start_stop array of start-stop beta par indeces for D matrix
#' @param prior_means real valued vector for holding prior mean information
#'  prior_means[0] = prior mean for intercept
#'  prior_means[1] = prior mean for delta coefs ... and so on
#' @param prior_scales real valued vector for holding prior scale information
#'  prior_scales[0] = prior scale for intercept
#'  prior_scales[1] = prior scale for delta coefs ... and so on
#' @param iter_max maximum number of iterations
#' @param max_treedepth max treedepth for NUTS
#' @param warm_up number of iterations to use for epsilon adaptation
#' @param seed random number generator seed
NULL

bbnet_lm_fit <- function(y, Z, DD, rpc, start_stop, prior_means, prior_scales, iter_max, max_treedepth, warm_up, seed) {
    .Call(`_bbnet_bbnet_lm_fit`, y, Z, DD, rpc, start_stop, prior_means, prior_scales, iter_max, max_treedepth, warm_up, seed)
}

